name = "exercisenow"
compatibility_date = "2024-12-18"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "fittrack"
database_id = "7fb370d2-3062-41af-a34d-aa3dafa2d614"
